SiCoBotero/urls.py
# -*- encoding: utf-8 -*-
import django
from django.conf.urls import patterns, include, url
from django.conf import settings
from Sistema_Principal import urls
from Sistema_Principal.views import *
import Sistema_Principal
from django.views.generic import RedirectView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SiCoBotero.views.home', name='home'),
    # url(r'^SiCoBotero/', include('SiCoBotero.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$',RedirectView.as_view(url="login")),
    url(r'^admin/', include(admin.site.urls),name="admin"),
    url(r'^',include(Sistema_Principal.urls),name="cotizador"),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
)

Sistema_Principal/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)
from django.contrib.auth.models import PermissionsMixin
from django.conf import settings
from django.contrib.auth.models import Group,Permission

# Create your models here.
class Empresa(models.Model):
    nombre = models.CharField(max_length=100,help_text=("Nombre de la Empresa"))
    nit = models.CharField(max_length=10,null=False,unique=True,verbose_name="NIT")
    ciudad = models.CharField(max_length=50,null=False)
    direccion = models.CharField(max_length=200,help_text=("Direccion de la Empresa"))
    telefono = models.CharField(max_length=10, help_text=("Telefono de la Empresa"))
    imagen = models.ImageField(upload_to="logos/")
    correo = models.EmailField(max_length=75)
    cuotas_no_aplic = models.IntegerField(max_length=1,null=False,verbose_name="Cuotas No Aplicadas")
    def __unicode__(self):
        return self.nombre
    class Meta:
        verbose_name="Empresa"
        verbose_name_plural="Empresas"
    
class UsuarioManager(BaseUserManager):
    def create_user(self,username,email,nombre=None,apellidos=None,password=None):
        if not username:
            raise ValueError('El usuario debe tener un nombre')
        user = self.model(
            username=username,
            email=UsuarioManager.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        user.save()
        return user
    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email=email,
            password=password,
            username=username,
        )
        user.is_superuser = True
        user.es_admin = True
        sicobotero = Empresa.objects.filter(nombre="SiBotero",nit="00000-0",ciudad="Cartagena",cuotas_no_aplic = 0)
        if(sicobotero.count() == 0):
            sicobotero = Empresa.objects.create(nombre="SiBotero",nit="00000-0",ciudad="Cartagena",cuotas_no_aplic = 0)
            sicobotero.save()
        user.empresa.add(sicobotero[0])
        user.ciudad = "Cartagena"
        user.save(using=self._db)
        return user
    def get_by_natural_key(self,username):
        return self.get(username=username)
    
class Usuario(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=40, unique=True, db_index=True, verbose_name='Usuario')
    email = models.EmailField(max_length=254, unique=True)
    telefono = models.CharField(max_length=25)
    nombre = models.CharField(max_length=20,help_text=("Nombre del vendedor"))
    apellidos = models.CharField(max_length=40,help_text=("Apellidos del vendedor"))
    empresa = models.ManyToManyField(Empresa)
    esta_activo = models.BooleanField(default=True,verbose_name="¿Esta activo?")
    es_admin = models.BooleanField(default=False,verbose_name="¿Es administrador?")
    ciudad = models.CharField(max_length=24,verbose_name="Ciudad Establecida")
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    objets = UsuarioManager()
    class Meta:
        verbose_name="Usuario"
        verbose_name_plural="Usuarios"
    def get_full_name(self):
        # The user is identified by their email address
        return u"%s %s"%(self.nombre.decode('utf8'),self.apellidos.decode('utf8'))

    def get_short_name(self):
        # The user is identified by their email address
        return self.nombre

    def __unicode__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Administracion de permisos"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Tiene permiso para entrar a la aplicacion?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Es administrador?"
        # Simplest possible answer: All admins are staff
        return self.es_admin
    def is_active(self):
        return self.esta_activo

class Cliente(models.Model):
    cedula = models.CharField(max_length=20,help_text=("Cedula del Cliente"))
    nombre = models.CharField(max_length=20,help_text=("Nombre del Cliente"),null=False)
    apellidos = models.CharField(max_length=40,help_text=("Apellidos del Cliente"),null=False)
    direccion = models.CharField(max_length=200,help_text=("Direccion de Cliente"),null=False)
    telefono = models.CharField(max_length=10, help_text=("Telefono del Cliente"),null=False)
    email = models.CharField(max_length=60, help_text=("Correo del cliente"),null=False)
    not_por_email = models.BooleanField(verbose_name="Notificar por Email")
    es_vip = models.BooleanField(verbose_name="Usuario VIP")
    empresa = models.ForeignKey(Empresa)
    def __unicode__(self):
        return self.nombre+" "+self.apellidos+" : "+self.cedula
    class Meta:
        verbose_name="Cliente"
        verbose_name_plural="Clientes"
        unique_together=('cedula','empresa')


class Matricula(models.Model):
    nombre_ciudad = models.CharField(max_length=20,null=False)
    precio = models.IntegerField(max_length=20,null=False)
    empresa = models.ForeignKey(Empresa,null=False)
    def __unicode__(self):
        return self.nombre_ciudad
    class Meta:
        verbose_name="Documento"
        verbose_name_plural="Documentos"
        unique_together=('nombre_ciudad','empresa')

class Moto(models.Model):
    nombre_fabr = models.CharField(max_length=15,help_text=("Fabricante de la moto"),null=False,verbose_name="Nombre Fabricante")
    referencia = models.CharField(max_length=30,null=False,help_text=("Referencia de la moto"))
    modelo = models.CharField(max_length=30,help_text=("Modelo de la moto"),null=False)
    precio_publico = models.IntegerField(max_length=14,null=False,verbose_name="Precio al Publico")
    cuota_minima = models.IntegerField(max_length=15,null=False,verbose_name="Cuota Minima")
    empresa = models.ForeignKey(Empresa,null=False)
    imagen_preview = models.ImageField(verbose_name="Foto",upload_to="motos/",default="/static/cotizacion/img/no-moto-img.png")
    def __unicode__(self):
        return self.nombre_fabr+" "+self.referencia+" "+self.modelo
    def __srt__(self):
        return self.nombre_fabr+" "+self.referencia+" "+self.modelo
    def delete(self, using=None):
        obj = Inventario_motos.objects.get(moto = self)
        obj.en_venta = False
    class Meta:
        verbose_name="Moto"
        verbose_name_plural="Motos"
        unique_together = ('modelo','referencia','empresa')

class Kit(models.Model):
    soat = models.IntegerField(max_length=10, null=False,verbose_name="SOAT")
    casco = models.IntegerField(max_length=10, null=False)
    chaleco = models.IntegerField(max_length=10, null=False)
    transporte = models.IntegerField(max_length=10, null=False)
    placa = models.IntegerField(max_length=10,null=False,verbose_name="Matricula")
    empresa = models.ForeignKey(Empresa,null=False)
    moto_asociada = models.ForeignKey(Moto,verbose_name="Moto Asociada")
    valor_prenda = models.IntegerField(max_length=10)
    def __unicode__(self):
        return self.moto_asociada.nombre_fabr+" "+self.moto_asociada.referencia+" "+self.moto_asociada.modelo
    def totalkit(self,conprenda=False):
        total = self.soat+self.casco+self.chaleco+self.transporte+self.placa
        if conprenda:
            total+=self.valor_prenda
        return total
    class Meta:
        verbose_name="Kit"
        verbose_name_plural="Kits"
        unique_together=('empresa','moto_asociada')

class Inventario_motos(models.Model):
    moto = models.ForeignKey(Moto,null=False,unique=True)
    en_venta = models.BooleanField(null=False,verbose_name="¿En venta?")
    empresa = models.ForeignKey('Empresa',null=False)
    def __unicode__(self):
        #return u'{0} {1}'.format(self.moto, self.en_venta)
        return self.moto.nombre_fabr+" "+self.moto.referencia
    class Meta:
        verbose_name = verbose_name_plural = "Inventario de Motos"
        unique_together=('empresa','moto')

    
class T_financiacion(models.Model):
    num_meses = models.IntegerField(max_length=2,null=False,verbose_name="Meses")
    valor_por = models.FloatField(null=False,verbose_name="Valor Porcentual")
    empresa = models.ForeignKey(Empresa,null=False)
    def __unicode__(self):
        return str(self.num_meses)
    class Meta:
        verbose_name="Registro de Financiacion"
        verbose_name_plural = "Registros de Financiacion"
        unique_together = ('num_meses','empresa')

class Medio_Publicitario(models.Model):
    identificador = models.IntegerField(max_length=3)
    medio = models.CharField(max_length="30",verbose_name="Medio Publicitario",null=False,blank=False)
    empresa = models.ForeignKey(Empresa)
    def __unicode__(self):
        return "%s %s"%(self.identificador,self.medio)
    class Meta:
        verbose_name= "Medio Publicitario"
        verbose_name_plural= "Medios Publicitarios"

class RequisitoTabla(models.Model):
    tipousuario = models.CharField(max_length=42,verbose_name="Tipo de Cliente")
    empresa = models.ForeignKey(Empresa,null=False)
    def __unicode__(self):
        return u"%s"%(self.tipousuario)
    class Meta:
        verbose_name="Tabla de Requisitos"
        verbose_name_plural="Tablas de Requisitos"

class registroRequisito(models.Model):
    tabla = models.ForeignKey(RequisitoTabla,null=False)
    requisito = models.CharField(max_length=200,null=False)
    def __unicode__(self):
        return u"%s"%self.requisito

class Cotizacion(models.Model):
    numeracion = models.IntegerField(max_length=100)
    fecha_cot = models.DateField(auto_now=True,verbose_name="Fecha de cotización")
    vendedor = models.ForeignKey(settings.AUTH_USER_MODEL)
    cliente = models.ForeignKey(Cliente)
    no_aplicables = models.BooleanField()

Sistema_Principal/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from Sistema_Principal.models import Cotizacion,Moto,Empresa,Cliente,Medio_Publicitario,T_financiacion

class AgregarCliente(forms.Form):
    cedula = forms.IntegerField(help_text=("Cedula del Cliente"),required=True,widget=forms.TextInput(attrs={'class':'required'}))
    nombre = forms.CharField(max_length=20,help_text=("Nombre del Cliente"),required=True,widget=forms.TextInput(attrs={'class':'required'}))
    apellidos = forms.CharField(max_length=40,help_text=("Apellidos del Cliente"),required=True,widget=forms.TextInput(attrs={'class':'required'}))
    direccion = forms.CharField(max_length=200,help_text=("Direccion de Cliente"),required=True, widget=forms.Textarea)
    telefono = forms.CharField(max_length=10, help_text=("Telefono del Cliente"),required=True,widget=forms.TextInput(attrs={'class':'required'}))
    email = forms.EmailField(max_length=60, help_text=("Correo del cliente"),required=True)
    not_por_email = forms.BooleanField(required=False)

class CotizacionMaestro(forms.ModelForm):
    class Meta:
        model = Cotizacion
        exclude = ['empresa','fecha_cot','vendedor','numeracion']

    def cleanned_cliente(self):
        value = self.cleaned_data['cliente']
        data = Cliente.objects.get(id=value)
        if data != None:
            return value
        else:
            raise forms.ValidationError("No puede dejar el campo cliente en blanco")

    def cleaned_medio(self):
        value = self.cleaned_data['medio']
        data = Medio_Publicitario.objects.get(id=value)
        if data != None:
            return value
        else:
            raise forms.ValidationError("¿Por que medio se entero el cliente?")

class Add_t_financiacion_form(forms.ModelForm):
    def cleanned_num_meses(self):
        if self.cleane_data['num_meses'] == None:
            raise forms.ValidationError("No puede dejar el numero de meses vacio")
    def clean(self):
        cleaned_data = super(Add_t_financiacion_form,self).clean()
        val = cleaned_data['num_meses']
        print cleaned_data
        print self.instance
        print self.instance.id
        if self.instance.id is None:
            t = T_financiacion.objects.filter(empresa=self.request.session['enterprise'],num_meses = val)
            if(t.count() > 0):
                raise forms.ValidationError("Ya existe un registro para ese numero de meses")
            else:
                return cleaned_data
        else:
            t = T_financiacion.objects.filter(empresa=self.request.session['enterprise'],num_meses = val).exclude(id=self.instance.id)
            print t.count()
            if(t.count()==0):
                return cleaned_data
            else:
                raise forms.ValidationError("Ya existe un registro para ese numero de meses")
    class Meta:
        model=T_financiacion
        exclude = ['empresa']

templates/cotizador/base.html
<!DOCTYPE html>
<html lang="es-co" >
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<head>
<title>Sistema de Cotización | SiCoBotero</title>
<link rel="stylesheet" type="text/css" href="/static/cotizacion/base.css">
<link rel="stylesheet" type="text/css" href="/static/cotizacion/dashboard.css">
<link rel="stylesheet" type="text/css" href="/static/cotizacion/js/select2/select2.css">
{% block css %}{% endblock %}
<script type="text/javascript" language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script type="text/javascript" src="/static/cotizacion/js/select2/select2.js"></script>
<!--[if IE]>
<script type="text/javascript" src="/static/cotizacion/json.js"></script>
<![endif]-->
{% block scripts %}
{% endblock %}
</head>
<body class="dashboard">

<!-- Header -->
    <div id="header">
        <div id="branding">

            {% if request.session.url_image != null %}
                <img src="{{ request.session.url_image }}" />
            {% endif %}

        <h1>{{ request.session.enterprise.nombre }}</h1>
        </div>

        <div id="user-tools">
            Bienvenido/a,
            <strong>{{ request.user.nombre }}</strong>.
                {% if request.user.is_staff %}
                <a href="">Cambiar contraseña</a> /
                {% endif %}
                <a href="{% url 'logout' %}">Terminar sesión</a>

        </div>


    </div>
    <!-- END Header -->

<!-- Container -->
<div id="container">
    <!-- Content -->
    <div id="content">


    <div id="content-main">
    {% block content-main %}


    {% endblock %}
    </div>
    <!-- END Content -->
</div>
<!-- END Container -->
</div>

{% if not is_popup %}
        <div id="sidebar">
        {% block sidebar %}
        {% endblock %}
        </div>
    {% endif %}

<div id="footer">
        <p>

        </p>
</div>
<!--Footer-->

</body>
</html>

templates/cotizador/cotizador.html
{% extends "cotizador/base.html" %}
{% load extratags %}
{% block css %}
<link rel="stylesheet" type="text/css" href="/static/cotizacion/aside.css">
<link rel="stylesheet" type="text/css" href="/static/cotizacion/cotizador.css">
{% endblock %}
{% block scripts %}
<script src="/static/cotizacion/js/jquery.formset.min.js" type="text/javascript" ></script>
<script>
    $(document).ready(function(){
    $("#id_cliente option[value='']").remove();
    $("#id_cliente").select2();
    $("#id_medio").select2();
    $("#id_requisitos").select2();
        {% if not is_inerror %}
            add_row();
        {% endif %}
    $("#add_moto").click(function(event){
        event.preventDefault();
        add_row();
    });
    $("#cotizar").click(function(event){
       event.preventDefault();
       $("#cotizacion").submit();
    });
    $(".select2menu").select2();
    $(".select2mult").select2();
    function add_row(){
        rows = $("#rows");
        if(parseInt(rows.val())<8){
        rows.val(parseInt(rows.val())+1);
            $.get("/get_row/"+rows.val(),function(data){
                $("#hijos").append(data);
                $("#id_moto_"+rows.val()).select2();
                $("#id_n_cuotas_"+rows.val()).select2();
            });
        }else{
            alert("Maximo 8 motos por cotizacion")
        }
    };
    });
</script>
{% endblock %}
{% block content-main %}
<h1>Cotizacion</h1>
<form method="POST" action="/cotizacion/" id="cotizacion">{% csrf_token %}
<table id="maestro">
<tr><th><label for="id_cliente">Cliente:</label></th><td>{{ form.cliente }}<a href="/agregar_cliente/" target="_blank" onClick="window.open(this.href, this.target, 'width=500,height=600'); return false;"><img src="/static/cotizacion/img/list-add.png" /></a>{{ form.cliente.errors }}</td></tr>
<tr><th><label for="id_no_aplicables">No aplicables:</label></th><td>{{ form.no_aplicables }}{{ form.no_aplicables.errors }}</td></tr>
<tr><th><label for="id_medio">Medio:</label></th><td>{{ form.medio }}{{ form.medio.errors }}</td></tr>
<tr><th><label for="id_requisitos">Requisitos: </label></th><td>{{ form.requisitos }}{{ form.requisitos.errors }}</td></tr>
</table>
<a href="#" id="add_moto" class="button"> <span>Añadir Moto</span></a>

<table>
    <thead>
    <tr>
    <td>
        Moto
    </td>
    <td>
        Cuota Inicial
    </td>
    <td>
        No. de Cuotas
    </td>
    <td>
        Tipo de Cotizacion.
    </td>
    </tr>
    </thead>
    {% autoescape off %}
    <tbody id="hijos">

        {{ contenttable }}

    </tbody>
    {% endautoescape %}
</table>
<ul class="errorlist">
{% for error in errors %}
    <li>{{ error }}</li>
{% endfor %}
</ul>
<input id="rows" type="hidden" value="{{ inline }}" name="rows"/>
<a id="cotizar" href="#" class="button">Cotizar</a>
</form>
{% endblock %}

{% block sidebar %}

        <div class="menu-item">
        {% if request.user.is_staff %}
        <h4><a href="#">Administracion</a></h4>
        <ul>
                    <li><a href="/admin/Sistema_Principal/cliente/">Clientes</a></li>

                    {% if request.user.is_superuser %}
                    <li><a href="/admin/Sistema_Principal/empresa/">Empresas</a></li>
                    {% endif %}
                    <li><a href="/admin/Sistema_Principal/inventario_motos/">Inventario de Motos</a></li>

                    <li><a href="/admin/Sistema_Principal/kit/">Kits</a></li>

                    <li><a href="/admin/Sistema_Principal/matricula/">Matriculas</a></li>

                    <li><a href="/admin/Sistema_Principal/medio_publicitario/">Medios Publicitarios</a></li>

                    <li><a href="/admin/Sistema_Principal/moto/">Motos</a></li>

                    <li><a href="/admin/Sistema_Principal/t_financiacion/">Registros de Financiacion</a></li>

                    <li><a href="/admin/Sistema_Principal/requisitotabla/">Requisitos para Financiacion</a></li>

                    <li><a href="/admin/Sistema_Principal/usuario/">Usuarios</a></li>
      </ul>
    </div>

    <div class="menu-item">
      <h4><a href="#">Reportes</a></h4>
      <ul>
        <li><a href="/historial_cotizaciones/">Historial de Cotizaciones</a></li>
      </ul>
    </div>
    {% endif %}
    <div class="menu-item">
      <h4><a href="#">Aplicaciones</a></h4>
        <ul>
            <li><a id="cot-panel" href="/cotizacion/"><img src="/static/cotizacion/img/wallet.png"/><br>Cotizacion</a></li>
        </ul>
      </div>

{%endblock %}

templates/cotizador/form_cliente.html
<!DOCTYPE html>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="/static/cotizacion/base.css">
    <title>Agregar Nuevo Cliente</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script>
        $('#ag_cli').click(function(){
            $("#formu").submit();
            window.opener.location.reload();
        });
    </script>
</head>
<body>
<form id="formu" action="/agregar_cliente/" method="POST">{% csrf_token %}
<fieldset>
<p>
    {{ form.cedula.errors }}
    <label class="field" for="id_cedula">Cedula:</label>{{ form.cedula }}<br /><span class="helptext">Cedula del Cliente</span>
</p>
<p>
    {{ form.nombre.errors }}
    <label class="field" for="id_nombre">Nombre:</label>{{ form.nombre }}<br /><span class="helptext">Nombre del Cliente</span>
</p>
<p>
    {{ form.apellidos.errors }}
    <label class="field" for="id_apellidos">Apellidos:</label>{{ form.apellidos }}<br/><span class="helptext">Apellidos del Cliente</span>
</p>
<p>
    {{ form.direccion.errors }}
    <label class="field" for="id_direccion">Direccion:</label>{{ form.direccion }}<br /><span class="helptext">Direccion de Cliente</span>
</p>
<p>
    {{ form.telefono.errors }}
    <label class="field" for="id_telefono">Telefono:</label>{{ form.telefono }}<br /><span class="helptext">Telefono del Cliente</span>
</p>
<p>
    {{ form.email.errors }}
    <label class="field" for="id_email">Email:</label>{{ form.email }}<br /><span class="helptext">Correo del cliente</span>
</p>
<p><label class="field" for="id_not_por_email">Not por email:</label>{{ form.not_por_email }}</p>
<input id="ag_cli" type="submit" value="Agregar">
</fieldset>
</form>
</body>
</html>

templates/cotizador/inline_fila_cotizacion.html
{% load extratags %}
<tr><td><select id="id_moto_{{ numero_inline }}" name="moto_{{ numero_inline }}" class="select2menu">
    {% for moto in motos %}
    <option value="{{ moto.id }}" class="moto" {% if moto.id == motosel.id %}selected="selected"{% endif %}>{{ moto.nombre_fab }} {{ moto.referencia }} {{ moto.modelo }}</option>
    {% endfor %}
</select></td>
<td>
    <input type="text" class="input" id="id_cuota_inicial_{{ numero_inline }}" name="cuota_inicial_{{ numero_inline }}" value="{{ cinicial }}"/>
</td>
<td>
    <select id="id_n_cuotas_{{ numero_inline }}" class="n_cuotas select2mult" name="n_cuotas_{{ numero_inline }}" multiple>
        {% for cuota in cuotas %}
            <option value="{{ cuota.id }}">{{ cuota.num_meses }}</option>
        {% endfor %}
    </select>
</td>
<td>
    <select id="id_tipo_{{ numero_inline }}"  name="id_tipo_{{ numero_inline }}">
        <option value="1">Credito</option>
        <option value="2">Contado</option>
    </select>
</td>
<td>
    <div id="prv_moto_{{ numero_inline }}">
    {% if not is_inerror %}
    <img src="{{ motos.0.imagen_preview.url }}" width="120px" />
    {% else %}
    <img src="{{ motosel.imagen_preview.url }}" width="120px" />
    {% endif %}
    </div>
</td>
</tr>
<script>
    $(document).ready(function(){
        $("#id_tipo_{{ numero_inline }}").select2()
                .on("change",function(evt){
                    sel = $("#id_tipo_{{ numero_inline }}").select2("val")
                    if(sel == 1){
                        $("#id_n_cuotas_{{ numero_inline }}").select2("enable",true);
                        $("#id_cuota_inicial_{{ numero_inline }}").attr("disabled",false);;
                    }else if (sel == 2){
                        $("#id_n_cuotas_{{ numero_inline }}").select2("enable",false);
                        $("#id_cuota_inicial_{{ numero_inline }}").attr("disabled",true);
                    }
                })
        $("#id_n_cuotas_{{ numero_inline }}").select2()
                .on("change",function(){
                    vals = $("#id_n_cuotas_{{ numero_inline }}").select2("val")
                    $("#id_n_cuotas_{{ numero_inline }}").select2("val","")
                    $("#id_n_cuotas_{{ numero_inline }}").select2("val",vals)

                })
        $("#id_moto_{{ numero_inline }}").select2()
                .on("change",function(){
                    id_moto = $("#id_moto_{{ numero_inline }}").select2("val")
                    $.get("/getimagen/"+id_moto+"/",function(data){
                                $("#prv_moto_{{ numero_inline }}").html(data);
                            });
                });

    })
</script>

templates/cotizador/reporte.html
{% extends "cotizador/base.html" %}
{% load extratags %}
{% block css%}
    <link href="/static/cotizacion/base.css" rel="stylesheet" type="text/css">
    <link href="/static/cotizacion/reporte.css" rel="stylesheet" type="text/css">
    <link href="/static/cotizacion/aside.css" rel="stylesheet" type="text/css">
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $("#topdf").click(function(event){
            event.preventDefault()
            window.open("/reportepdf/{{ cot.id }}/","_blank",'width=800,height=600');
        });
    });
</script>
{% endblock %}

{% block content-main %}
<div id="header_reporte">
    {% if request.session.url_image != null %}
                <img src="{{ request.session.url_image }} "  width='160px' height='110px'/>
    {% endif %}
    <h1><span>Cotizacion Fecha : </span>{{ cot.fecha_cot }}</h1>
</div>
<div id ="body_reporte">
<h1>{{ request.session.enterprise.nombre }}</h1>
<div id="left_side">
<h2>Numeracion : {{ cot.numeracion }}</h2>
<h2>Cliente : {{ cot.cliente.nombre }} {{ cot.cliente.apellidos }}</h2>
<h2>Vendedor : {{ cot.vendedor.nombre }} {{ cot.vendedor.apellidos }}</h2>
<h2>Medio : {{ cot.medio.identificador }} {{ cot.medio.medio }}</h2>
</div>
<div id="right_side">
{% autoescape off %}
  {{ tablas }}
{% endautoescape %}
</div>
</div>
    <div id="options">
        <a href="/pdfacorreo/{{ cot.id }}/"><img src="/static/cotizacion/img/mail-forward.png">Enviar Email</a>
        <a id="topdf" href="#"><img src="/static/cotizacion/img/acroread.png">Ver/Imprimir PDF</a></li>
        <a id="to_cotizador" href="/cotizacion/"><img src="/static/cotizacion/img/wallet.png">Cotizacion</a>
    </div>
{% endblock %}

{% block sidebar %}
    <div class="menu-item">
    {% if user.is_staff %}
      <h4><a href="#">Administracion</a></h4>
      <ul>
        <li><a id="cont-panel" href="{% url 'admin:index' %}"><img src="/static/cotizacion/img/display.png"/><br>Administración</a></li>
      </ul>
    </div>
    {% endif %}

    <div class="menu-item">
      <h4><a href="#">Reportes</a></h4>
      <ul>
        <li><a href="#">Medios/Impacto</a></li>
      </ul>
    </div>

{% endblock %}

templates/cotizador/thanks.html
<html>
<head>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script>

    function sleep(milliseconds) {
        var start = new Date().getTime();
        for (var i = 0; i < 1e7; i++) {
            if ((new Date().getTime() - start) > milliseconds){
                break;
            }
        }
    }
        sleep(2000);
        window.opener.location.reload();

</script>
</head>
<body>
    <img src="/static/cotizacion/img/text-directory.png" />
    <p>Cliente agregado correctamente.</p>
</body>
</html>